# Generated by Django 3.2.9 on 2021-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniuser',
            name='date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
