# Generated by Django 3.2.9 on 2021-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0002_alter_miniuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniuser',
            name='file',
            field=models.FileField(default=None, upload_to=None, verbose_name='Songs file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date added'),
        ),
    ]
