# Generated by Django 3.2.9 on 2021-11-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0004_alter_miniuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniuser',
            name='date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Songs file'),
        ),
    ]
