# Generated by Django 3.2.9 on 2021-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0006_auto_20211113_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='miniuser',
            options={'verbose_name': 'MiniUser', 'verbose_name_plural': 'MiniUsers'},
        ),
        migrations.AddField(
            model_name='miniuser',
            name='board_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Board name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Album name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(max_length=5, verbose_name='Album year'),
        ),
    ]
