# Generated by Django 3.2.9 on 2021-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0007_auto_20211113_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniuser',
            name='trelloKey',
        ),
        migrations.AddField(
            model_name='miniuser',
            name='trelloToken',
            field=models.CharField(default=0, max_length=50, verbose_name='trello token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='board_name',
            field=models.CharField(max_length=50, verbose_name='Board id'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Albums file'),
        ),
    ]
