# Generated by Django 3.2.9 on 2021-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0008_auto_20211113_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniuser',
            name='board_name',
            field=models.CharField(max_length=50, verbose_name='Board name'),
        ),
        migrations.AlterField(
            model_name='miniuser',
            name='trelloToken',
            field=models.CharField(max_length=100, verbose_name='trello token'),
        ),
    ]
