# Generated by Django 3.2.9 on 2021-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0009_auto_20211113_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniuser',
            name='spotifyToken',
            field=models.CharField(default=0, max_length=100, verbose_name='spotify token'),
        ),
    ]
