# Generated by Django 3.2.9 on 2021-11-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0010_miniuser_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniuser',
            name='spotifyToken',
            field=models.CharField(default=0, max_length=512, verbose_name='spotify token'),
        ),
    ]
