# Generated by Django 3.2.9 on 2021-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellofy', '0011_alter_miniuser_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Album name'),
        ),
    ]
