name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
          
#       - name: Start docker-compose
#         run: docker-compose up -d
        
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python-lxml libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev
          pip install --upgrade --upgrade-strategy eager -r requirements.txt
          pip install coverage flake8
          
      - name: Run migrations
        run: |
          python manage.py migrate
          
      # - name: Run tests
      #   run: |
      #     coverage run manage.py test
      #     coverage xml
 
      # - name: Upload coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
      #     verbose: true
      #     files: ./coverage.xml
          
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'test'  # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
